name: Build (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v2
      - name: Get Latest G++/GCC version
        run: sudo apt install gcc-11 g++-11
      - name: Set CXX=g++-11
        run: echo "CXX=g++-11" >> $GITHUB_ENV
      - name: Set CC=gcc-11
        run: echo "CC=gcc-11" >> $GITHUB_ENV
      - name: Build
        run: cd ${{github.workspace}} && make
